{% set version = "3.0.2" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}

package:
  name: qrcode-artistic-build
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/q/qrcode-artistic/qrcode-artistic-{{ version }}.tar.gz
    sha256: eb71f12673c89f638cf7252554a74ecbe4a22f1ce15920caa53da75a48c181f4
  - folder: src
    url: https://github.com/heuer/qrcode-artistic/archive/refs/tags/{{ version }}.tar.gz
    sha256: 11f2e9b5555bafef8e47be66200533d63ea897d5d9f892b2e4971cc313971d25

build:
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - echo "tests in subpackages"

outputs:
  - name: qrcode-artistic-base
    build:
      noarch: python
      script:
        - cd dist 
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
      run:
        - python >={{ python_min }}
        - pillow
        - segno >=1.0.2,<2
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - qrcode_artistic
      commands:
        - pip check

  - name: qrcode-artistic-svg
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("qrcode-artistic-base", exact=True) }}
        - cairosvg
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - qrcode_artistic
      commands:
        - pip check

  - name: qrcode-artistic
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("qrcode-artistic-base", exact=True) }}
        - {{ pin_subpackage("qrcode-artistic-svg", exact=True) }}
    test:
      source_files:
        - src/tests
        - src/images
      requires:
        - pip
        - pytest >=6,<7
        - pytest-cov
        - python {{ python_min }}
        - pyzbar >=0.1.9,<0.2  # [unix]
      imports:
        - qrcode_artistic
      commands:
        - pip check
        - cd src
        - pytest -vv --tb=long --color=yes --cov=qrcode_artistic --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=95  # [unix]

about:
  home: https://github.com/heuer/qrcode-artistic
  summary: Artistic (Micro) QR Code plugin for Segno
  license: BSD-3-Clause
  license_file: dist/LICENSE

extra:
  feedstock-name: qrcode-artistic
  recipe-maintainers:
    - bollwyvl
